server:
  port: 8887

# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
         
# Mapeo de Microservicios
spring:

  cloud:
    gateway:
      discovery.locator:    #A           
          enabled: true           
          lowerCaseServiceId: true
      routes:
      - id: ms-profile
        uri: lb://ms-profile
        predicates:
        - Path=/api/ms-profile/**
        filters:         
        - RewritePath=/ms-profile/(?<path>.*), /$\{path}
        
      - id: albums
        uri: https://jsonplaceholder.typicode.com/albums
        predicates:
        - Path=/albums
        
# Activacion de endpoints         
management:
     endpoints:
       web:
         exposure:
           include: '*'
     endpoint:
       health:
         show-details: always