server:  
  port: ${PORT:0}
  
  error:    
    include-message: always

#EUREKA CUSTOMER    

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


#DB MONGO

spring:
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      database: ms-customer
      repositories:
        enabled: true
        
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
