server:  
  port: ${PORT:0}
    
  error:    
    include-message: always

#EUREKA CUSTOMER    

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8889/eureka
  instance:
      instance-id: ${spring.application.name}:${random.value}
      prefer-ip-address: true


#DB MONGO

spring:
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      database: ms-creditcard
      repositories:
        enabled: true
        
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
